# script to generate data to csv

# run without an argument to regenerate the sql
# run with argument "new" to generate new data and regenerate the sql

# table for cities should take in more

import os
import sys
import pathlib
import random
from csv import DictReader
from collections.abc import Callable
# from typing import cast
from functools import partial
from faker import Faker

faker = Faker()
sql = True

with open("load_csv.sql", 'w') as f:
    _ = f.write(
            "-- automatically generated by generate_data.py\n" +
            "-- run 'generate_data.py' to generate correct path literal\n" +
            "-- run 'generate_data.py new' to generate new data\n"
            )

if(len(sys.argv) > 1 and sys.argv[1] == "new"):
    sql = False

# create table, then populate
def create_table(file_name: str, num_tuples: int,
                 attr_list: list[str], pk_list: list[str],
                 fk_list: dict[str, str], callable_list: list[Callable[[], object]],
                 exclude: dict[str, list[str]] = {}):

    write_sql(file_name)
    if(sql):
        return

    print("Generating " + file_name)

    # header that defines values
    with open(file_name+".csv", "w") as f:
        header = init_table(attr_list)
        _ = f.write(header+"\n")

    # get fk columns with usable values
    fk_columns: dict[str, list[str]] = get_fk_values(fk_list, exclude)

    # keep track of pk and ak for entry generation
    key_columns: list[set[str]] = []
    for pk in pk_list:
        key_columns.append(set())

    # entries
    with open(file_name+".csv", "a") as f:
        for i in range(num_tuples):
            entry = gen_entry(attr_list, callable_list, fk_columns, key_columns)
            _ = f.write(entry+"\n")


# populate header and faker_commands
def init_table(attr_list: list[str]) -> str:
    header: str=""

    for col in range(len(attr_list)):
        header+=attr_list[col]+","

    return header[:-1]

# populate entry
def gen_entry(attr_list: list[str], callable_list: list[Callable[[], object]], fk_columns: dict[str, list[str]], key_columns: list[set[str]]) -> str:
    entry: str=""

    col = 0
    while col < len(callable_list):
        # get val from existing fk val
        if attr_list[col] in fk_columns:
            rand = random.randrange(1, len(fk_columns[attr_list[col]]))
            command = fk_columns[attr_list[col]][rand]
        # else generate val via faker
        else:
            command = str(callable_list[col]())

        # if val already exists as key, redo
        if col < len(key_columns) and command in key_columns[col]:
            continue

        entry += command+","
        if col < len(key_columns):
            key_columns[col].add(command)

        col+=1

    return entry[:-1]

# get fk values
def get_fk_values(fk_list: dict[str, str], exclude: dict[str, list[str]]) -> dict[str, list[str]]:
    fk_columns: dict[str, list[str]] = {}

    for fk in fk_list:
        exclusion_list: list[str] = []

        # exclusion list: fk entries from relations in exclude
        if fk in exclude:
            for file in exclude[fk]:
                with open(file+".csv", "r") as f:
                    reader = DictReader(f)

                    for row in reader:
                        exclusion_list.append(row[fk])

        # get fk entries; exclude entries on exclusion list
        with open(fk_list[fk]+".csv", "r") as f:
            reader = DictReader(f)

            fk_columns[fk] = []
            for row in reader:
                if row[fk] not in exclusion_list:
                    fk_columns[fk].append(row[fk])

    return fk_columns

# write the sql statements to load the file into the db
def write_sql(file_name: str):
    slash = "\\" if os.name == "nt" else "/"
    path=f"{pathlib.Path(__file__).parent.resolve()}{slash}{file_name}.csv"

    with open("load_csv.sql", "a") as f:
        _ = f.write(
                "\n"+
                f"LOAD DATA LOCAL INFILE '{path}'\n"+
                f"INTO TABLE {file_name}\n"+
                "FIELDS TERMINATED BY ','\n"+
                "OPTIONALLY ENCLOSED BY '\"'\n"+
                "LINES TERMINATED BY '\\n'\n"+
                "IGNORE 1 LINES;\n"
                )

counter = 1

def ordered_date():
    global counter

    if(counter == 1):
        counter+=1
        return "2000-01-01"
    elif(counter == 2):
        counter-=1
        return "2000-01-02"

# some functions
default = partial(faker.pystr, min_chars=3, max_chars=10)
int = partial(random.randint, 0, 10000000)
small_int = partial(random.randint, 0, 1000)
small_decimal = partial(faker.pydecimal, min_value=0, max_value=9.0, right_digits=2)
large_decimal = partial(faker.pydecimal, min_value=0, max_value=100000.0, right_digits=2)

# tables
create_table("Employee", 2000,
             ["employee_id", "email", "f_name", "l_name", "birthday", "hours_worked", "salary"],            # attributes
             ["employee_id", "email"],                                                                      # keys (pk + ak)
             {},                                                                                            # foreign keys
             [int, faker.email, faker.first_name, faker.last_name, faker.date, small_int, small_decimal]    # callable
             )
create_table("SalesAssociate", 1000,
             ["employee_id", "commission_rate"],
             ["employee_id"],
             {"employee_id": "Employee"},
             [int, small_decimal]
             )
create_table("Manager", 100,
             ["employee_id", "bonus_rate"],
             ["employee_id"],
             {"employee_id": "Employee"},
             [int, small_decimal],
             exclude = {"employee_id": ["SalesAssociate"]})
create_table("Store", 75,
             ["store_id", "street", "city", "postcode", "employee_id"],
             ["store_id", "employee_id"],
             {"employee_id": "Manager"},
             [int, faker.street_address, faker.city, faker.postcode, int]
             )
create_table("Customer", 500,
             ["customer_id", "f_name", "l_name", "phone_number", "birthday", "gender", "email"],
             ["customer_id", "email", "phone_number"],
             {},
             [int, faker.first_name, faker.last_name, faker.phone_number, faker.date, faker.passport_gender, faker.email]
             )
create_table("Warehouse", 12,
             ["warehouse_id", "street", "city", "postcode", "sqft", "capacity"],
             ["warehouse_id"],
             {},
             [int, faker.street_address, faker.city, faker.postcode, large_decimal, int]
             )
# TODO: compound keys
create_table("Supplies", 5,#1000,
             ["store_id", "warehouse_id"],
             ["store_id", "warehouse_id"],
             {"store_id": "Store", "warehouse_id": "Warehouse"},
             [int, int]
             )
create_table("Supplier", 250,
             ["supplier_id", "supplier_name", "street", "city", "postcode", "phone", "email"],
             ["supplier_id", "email", "phone"],
             {},
             [int, faker.word, faker.street_address, faker.city, faker.postcode, faker.phone_number, faker.company_email]
             )
create_table("Product", 10000,
             ["product_id", "product_name", "brand", "category", "discount", "pricing", "supplier_id", "warehouse_id"],
             ["product_id"],
             {"warehouse_id": "Warehouse", "supplier_id": "Supplier"},
             [int, faker.word, faker.word, faker.word, small_decimal, large_decimal, int, int]
             )
create_table("Shipment", 1000,
             ["shipment_id", "store_id", "supplier_id", "order_date", "arrival_date", "num_pallet", "cost"],
             ["shipment_id"],
             {"store_id": "Store", "supplier_id": "Supplier"},
             [int, int, int, ordered_date, ordered_date, int, large_decimal]
             )
# another compound key
create_table("ProductShipment", 5,#1000,
             ["shipment_id", "product_id"],
             ["shipment_id", "product_id"],
             {"shipment_id": "Shipment", "product_id": "Product"},
             [int, int]
             )
create_table("Sale", 10,
             ["sale_id", "order_type", "customer_id", "employee_id", "product_id", "store_id", "sale_date"],
             ["sale_id"],
             {"customer_id": "Customer", "employee_id": "Employee", "product_id": "Product", "store_id": "Store"},
             [int, faker.word, int, int, int, int, faker.date]
             )
create_table("Advertisement", 10,
             ["ad_id", "ad_name", "channels", "budget", "product_id", "start_date", "end_date"],
             ["ad_id"],
             {},
             [int, faker.word, faker.word, large_decimal, ordered_date, ordered_date]
             )
# another composite
create_table("Ad_Product", 5,#100,
             ["ad_id", "product_id"],
             ["ad_id", "product_id"],
             {"ad_id": "Advertisement", "product_id": "Product"},
             [int, int]
             )
